// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace Assets.Scripts.Managers
{
public static class GooglePlayManager
{
        public const string achievement_dans_les_temps = "CgkI0qDllKYWEAIQCQ"; // <GPGSID>
        public const string achievement_mais_arrte_enfin = "CgkI0qDllKYWEAIQAg"; // <GPGSID>
        public const string achievement_dis_donc_a_sonne = "CgkI0qDllKYWEAIQBg"; // <GPGSID>
        public const string achievement_ae_mon_oeil = "CgkI0qDllKYWEAIQAQ"; // <GPGSID>
        public const string achievement_sacr_rythme = "CgkI0qDllKYWEAIQBA"; // <GPGSID>
        public const string achievement_quel_doux_bruit = "CgkI0qDllKYWEAIQAw"; // <GPGSID>
        public const string achievement_a_souffle_non = "CgkI0qDllKYWEAIQCg"; // <GPGSID>
        public const string achievement_quel_puissance = "CgkI0qDllKYWEAIQBw"; // <GPGSID>
        public const string achievement_je_vois_double = "CgkI0qDllKYWEAIQCA"; // <GPGSID>
        public const string achievement_de_la_tlportation = "CgkI0qDllKYWEAIQBQ"; // <GPGSID>

}
}
